version: '3.8'

services:
  users-service:
    build: .
#    volumes:
#      - ./users-service:/app
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=user-db
      - DB_USER=postgres
      - DB_PASSWORD=qwerty
      - DB_NAME=users
      - DB_PORT=5432
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  user-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  user_db_data:

networks:
  app-network:
    external: true